### ISSUE TITLE
Would love to see typescript definitions for sketch json

### ISSUE THREAD

**Issue by nojvek** [xaviervia/sketch-loader#4]

**Comment by xaviervia** [comment]
@nojvek that'd be a significant effort that I'm not able to undertake. Ideally Bohemian Coding should provide those (or at least a documentation from which they could be generated). And they will very likely change the format from time to time, so maintaining typescript definitions would be a continuous challenge. 

That said, @darknoon has a flow type specification that should be very helpful for typescript: https://github.com/darknoon/sketchapp-json-flow-types/blob/master/types.js
